language: python
dist: xenial
cache: pip
matrix:
  include:
    - python: 3.5-dev
      env: TOXENV=py35-asyncio,py35-uvloop
    - python: 3.6-dev
      env: TOXENV=py36-asyncio,py36-uvloop
    - python: 3.7-dev
      env: TOXENV=py37-asyncio,py37-uvloop
    - python: 3.8-dev
      env: TOXENV=py38-asyncio,py38-uvloop
  allow_failures:
    - python: 3.5-dev
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
script: tox
install:
  - 'pip install tox'
