variables:
  CI: 'true'
  EVENT_LOOP: 'asyncio'

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
        TOXENV: 'clean,py35-asyncio,py35-uvloop,coverage'
      Python36:
        python.version: '3.6'
        TOXENV: 'clean,py36-asyncio,py36-uvloop,coverage'
      Python37:
        python.version: '3.7'
        TOXENV: 'clean,py37-asyncio,py37-uvloop,coverage'
      PyPy3:
        python.version: 'pypy3'
        TOXENV: 'clean,pypy35-asyncio,coverage'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
    # Ubuntu 16.04 default Python is 3.5.2
    condition: ne(variables['python.version'], '3.5.2')
  - script: pip install tox tox-venv
    displayName: 'Install Tox'
  - script: tox
    displayName: 'Run Tox'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'test-results-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      failIfCoverageEmpty: true
